Updated code to 0.3
FifthTry/typography pull request #4
Opened 2023-01-09 13:29 UTC by MeenuKumari28

Updated code to FTD-0.3

2023-01-09 13:31 UTC, amitu commented on index.ftd
> +padding-horizontal.px if { ftd.device == "mobile" }: 20
@Arpita-Jaiswal Use `.responsive`?

2023-01-11 14:22 UTC, Arpita-Jaiswal requested changes

2023-01-11 14:22 UTC, Arpita-Jaiswal commented on index.ftd
> +;;append-at: inner -- TODO FTD 0.3
`append-at` is never going to come in `FTD 0.3`. Remove this line from everywhere

2023-01-11 14:22 UTC, Arpita-Jaiswal commented on index.ftd
> +;;id: inner -- TODO FTD 0.3
Why `id` is needed here? The purpose it serves earlier is not there anymore.

2023-01-11 14:22 UTC, Arpita-Jaiswal commented on index.ftd
> +if: {$h3.body != NULL}
```suggestion
if: { h3.body != NULL }
```

2023-01-11 14:22 UTC, Arpita-Jaiswal commented on index.ftd
> +margin-bottom.px if {$h3.body != NULL}: -26
```suggestion
margin-bottom.px if { h3.body != NULL }: -26
```

2023-01-11 14:22 UTC, Arpita-Jaiswal commented on index.ftd
> +margin-bottom.px if {$h2.body != NULL}: -26
Don't use `$` in FScript mode (i.e. inside `{}`). Also, use space after `{` and before `}`.
```suggestion
margin-bottom.px if { h2.body != NULL }: -26
```

2023-01-11 14:22 UTC, Arpita-Jaiswal commented on index.ftd
> +if: {$h2.body != NULL}
```suggestion
if: { h2.body != NULL }
```

2023-01-11 14:22 UTC, Arpita-Jaiswal commented on index.ftd
> +margin-bottom.px if {$h4.body != NULL}: -26
```suggestion
margin-bottom.px if { h4.body != NULL }: -26
```

2023-01-11 14:22 UTC, Arpita-Jaiswal commented on index.ftd
> +if: {$h4.body != NULL}
```suggestion
if: { h4.body != NULL }
```

2023-01-11 14:22 UTC, Arpita-Jaiswal commented on index.ftd
> +if: {$key-value.value != NULL}
```suggestion
if: { key-value.value != NULL }
```

2023-01-11 14:22 UTC, Arpita-Jaiswal commented on index.ftd
> +if: {$key-value.value = NULL}
```suggestion
if: { key-value.value = NULL }
```

2023-01-11 14:22 UTC, Arpita-Jaiswal commented on index.ftd
> +;;$on-click$: toggle $open -- TODO FTD 0.3
```suggestion
$on-click$: $ftd.toggle($a = $open)
```

2023-01-11 14:22 UTC, Arpita-Jaiswal commented on index.ftd
> +padding-horizontal.px if { ftd.device == "mobile" }: 20
This is fixed @amitu.

2023-01-12 23:01 UTC, merged